#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP -d 1 2 3 4
bspc monitor DisplayPort-0 -d 5

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

bspc rule -a Matplotlib state=floating

# Autostart

~/.config/polybar/launch.sh &

picom &

~/.config/bspwm/scripts/cleanfullscreen.sh &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

nitrogen --restore &

#dex -a -s /etc/xdg/autostart/:~/.config/autostart/
