#! /bin/sh

DIR="$HOME/.config/bspwm"
export PATH="${PATH}:$DIR/scripts"

bspc monitor eDP -d 1 2 3 4
bspc monitor DisplayPort-0 -d 5

bspc config border_width        2
bspc config window_gap          10
bspc config split_ratio         0.65

bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

bspc rule -a Matplotlib state=floating

pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd -c "$DIR"/sxhkdrc &
"$DIR"/polybar/polybar.sh &
bspcomp &
cleanfullscreen &
nitrogen --restore &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
