#! /bin/sh

## Bspwm config directory
DIR="$HOME/.config/bspwm"
## Export bspwm/bin dir to PATH
export PATH="${PATH}:$DIR/scripts"

bspc monitor eDP -d 1 2 3 4
bspc monitor DisplayPort-0 -d 5

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

bspc rule -a Matplotlib state=floating

# Autostart

pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd -c "$DIR"/sxhkdrc &
"$DIR"/polybar/polybar.sh &
bspcomp &
cleanfullscreen &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

nitrogen --restore &
